osx_image: xcode10.2
language: objective-c
cache: cocoapods
jobs:
  include:
    - stage: Testing
      before_install:
      - gem install cocoapods
      - pod install --project-directory=Example
      script:
      - xcodebuild test -enableCodeCoverage YES -workspace Example/AttributedString.swift.xcworkspace -scheme AttributedString.swift-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XÊ€' -quiet
      - pod lib lint --allow-warnings
    - stage: deploying to cocoapods
      before_install:
        - echo $TRAVIS_TAG
        - export LIB_VERSION=$TRAVIS_TAG
        - gem install cocoapods
      script:
        - pod lib lint --allow-warnings
        - pod trunk push --allow-warnings
      if: tag IS present
